database:
  driverClass: org.postgresql.Driver
  user: voldemort
  password: hewhomustnotbenamed
  url: jdbc:postgresql:assignment_6

  properties:
    charSet: UTF-8
  
  maxWaitForConnection: 1s
  validationQuery: "/* Postgres Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false

server:
  adminMinThreads: 1
  adminMaxThreads: 64
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8090
      keyStorePath: src/main/resources/store/keystore.jks
      keyStorePassword: bestpassword
      validateCerts: false
      certAlias: csc435

logging:
  level: INFO
  loggers:
    brendan.csc435: DEBUG